[workspace]
members = ["crates/fjord", "crates/fjord-broker", "crates/fjord-coordinator", "crates/fjord-heimq-backend", "crates/fjord-log", "crates/fjord-object-log"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.82"
authors = ["Erik LaBianca <erik@telepathdata.com>"]
license = "MIT"
repository = "https://github.com/telepathdata/fjord"
