# SPDX-License-Identifier: Apache-2.0

name: fjord resource full - 1 topic / 12 partitions / 1KiB
topics: 1
partitionsPerTopic: 12
messageSize: 1024
payloadFile: "payload/payload-1Kb.data"
subscriptionsPerTopic: 1
consumerPerSubscription: 1
producersPerTopic: 4
producerRate: 0
consumerBacklogSizeGB: 0
testDurationMinutes: 60
