#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
MANIFEST="$ROOT/docs/public/data/capabilities.json"
PAGE="$ROOT/docs/public/src/compatibility.md"
BEADS="$ROOT/.ddx/beads.jsonl"
MODE=${1:-render}

if [[ "$MODE" != "render" && "$MODE" != "--check" ]]; then
  echo "usage: ${0##*/} [--check]" >&2
  exit 2
fi

for command in jq git awk; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "$command is required" >&2
    exit 2
  fi
done

for file in "$MANIFEST" "$PAGE" "$BEADS"; do
  if [[ ! -f "$file" ]]; then
    echo "required file is missing: ${file#"$ROOT"/}" >&2
    exit 2
  fi
done

jq -e '
  .schema_version == 1 and
  (.documented_release | type == "string" and length > 0) and
  (.release_commit | type == "string" and test("^[0-9a-f]{40}$")) and
  ((.status_definitions | keys | sort) ==
    (["Design target", "Experimental", "Unimplemented", "Verified"] | sort)) and
  (.capabilities | type == "array" and length > 0) and
  all(.capabilities[];
    (.id | type == "string" and length > 0) and
    (.title | type == "string" and length > 0) and
    (.status | IN("Design target", "Verified", "Experimental", "Unimplemented")) and
    (.design_refs | type == "array" and length > 0 and all(.[]; type == "string" and length > 0)) and
    (.evidence | type == "array" and all(.[];
      (.kind | IN("release_source", "release_test", "release_command", "release_dependency")) and
      (.ref | type == "string" and length > 0))) and
    (.bead_ids | type == "array" and all(.[]; type == "string" and length > 0)) and
    (.limitations | type == "array" and all(.[]; type == "string" and length > 0)) and
    (if has("advertised_kafka_api") then
      (.advertised_kafka_api.key | type == "number") and
      (.advertised_kafka_api.name | type == "string" and length > 0) and
      (.advertised_kafka_api.min_version | type == "number") and
      (.advertised_kafka_api.max_version | type == "number") and
      (.advertised_kafka_api.min_version <= .advertised_kafka_api.max_version)
    else true end)) and
  (([.capabilities[].id] | length) == ([.capabilities[].id] | unique | length)) and
  (([.capabilities[] | select(has("advertised_kafka_api")) | .advertised_kafka_api.key] | length) ==
    ([.capabilities[] | select(has("advertised_kafka_api")) | .advertised_kafka_api.key] | unique | length)) and
  all(.capabilities[] | select(.status == "Verified");
    any(.evidence[]; .kind == "release_test" or .kind == "release_command")) and
  all(.capabilities[] | select(.status == "Experimental");
    (.limitations | length > 0) and (.bead_ids | length > 0)) and
  all(.capabilities[] | select(.status == "Unimplemented"); .bead_ids | length > 0)
' "$MANIFEST" >/dev/null

documented_release=$(jq -r '.documented_release' "$MANIFEST")
manifest_commit=$(jq -r '.release_commit' "$MANIFEST")
if ! release_commit=$(git -C "$ROOT" rev-list -n 1 "$documented_release" 2>/dev/null); then
  echo "documented release does not resolve locally: $documented_release" >&2
  exit 1
fi
if [[ "$release_commit" != "$manifest_commit" ]]; then
  echo "release_commit does not match $documented_release" >&2
  echo "manifest: $manifest_commit" >&2
  echo "tag:      $release_commit" >&2
  exit 1
fi

missing_beads=$(
  comm -23 \
    <(jq -r '.capabilities[].bead_ids[]' "$MANIFEST" | sort -u) \
    <(jq -r '.id' "$BEADS" | sort -u)
)
if [[ -n "$missing_beads" ]]; then
  echo "capability manifest references unknown beads:" >&2
  echo "$missing_beads" >&2
  exit 1
fi

fragment=$(mktemp)
page_tmp=$(mktemp)
trap 'rm -f "$fragment" "$page_tmp"' EXIT

start_markers=$(grep -c '<!-- capability-matrix:start -->' "$PAGE" || true)
end_markers=$(grep -c '<!-- capability-matrix:end -->' "$PAGE" || true)
if [[ "$start_markers" -ne 1 || "$end_markers" -ne 1 ]]; then
  echo "compatibility page must contain exactly one capability matrix marker pair" >&2
  exit 1
fi

{
  echo "<!-- Generated by scripts/render-capabilities.sh. -->"
  echo
  echo "**Documented release:** \`$documented_release\` (\`$manifest_commit\`)"
  echo
  verified_count=$(jq '[.capabilities[] | select(.status == "Verified")] | length' "$MANIFEST")
  experimental_count=$(jq '[.capabilities[] | select(.status == "Experimental")] | length' "$MANIFEST")
  unimplemented_count=$(jq '[.capabilities[] | select(.status == "Unimplemented")] | length' "$MANIFEST")
  target_count=$(jq '[.capabilities[] | select(.status == "Design target")] | length' "$MANIFEST")
  advertised_count=$(jq '[.capabilities[] | select(has("advertised_kafka_api"))] | length' "$MANIFEST")
  echo "**Status summary:** $verified_count verified, $experimental_count experimental,"
  echo "$unimplemented_count unimplemented, and $target_count design targets. The broker"
  echo "advertises $advertised_count Kafka APIs, but advertising is not verification."
  echo
  echo "### Verified Workflows"
  echo
  jq -r '
    def html: tostring | @html;
    .capabilities[] | select(.status == "Verified") |
    "<details class=\"capability-entry\" open>\n" +
    "<summary><strong>" + (.title | html) + "</strong> <span>Verified</span></summary>\n" +
    "<p><strong>Release evidence:</strong><br>" +
      ([.evidence[].ref | "<code>" + html + "</code>"] | join("<br>")) + "</p>\n" +
    "<p><strong>Current constraint:</strong> " +
      ((.limitations | join(" ")) | html) + "</p>\n" +
    "</details>\n"
  ' "$MANIFEST"

  for status in Experimental Unimplemented "Design target"; do
    case "$status" in
      Experimental) heading="Experimental System Capabilities" ;;
      Unimplemented) heading="Unimplemented System Capabilities" ;;
      "Design target") heading="Design Targets Outside the Current Release" ;;
    esac
    echo
    echo "### $heading"
    echo
    jq -r --arg status "$status" '
      def html: tostring | @html;
      .capabilities[] |
      select(.status == $status and (has("advertised_kafka_api") | not)) |
      "<details class=\"capability-entry\">\n" +
      "<summary><strong>" + (.title | html) + "</strong></summary>\n" +
      "<p><strong>Current constraint:</strong> " +
        ((.limitations | join(" ")) | html) + "</p>\n" +
      "</details>\n"
    ' "$MANIFEST"
  done

  echo
  echo "### Advertised Kafka API Audit"
  echo
  echo "The following ranges come from the release broker's ApiVersions response."
  echo "Use the release status and constraint columns to decide whether a workflow is"
  echo "suitable for evaluation. Exact evidence and tracking metadata remain in the"
  echo "[machine-readable manifest](https://github.com/7thsense/fjord/blob/main/docs/public/data/capabilities.json)."
  echo
  jq -r '
    def html: tostring | @html;
    .capabilities[] | select(has("advertised_kafka_api")) |
    "<details class=\"api-entry\">\n" +
    "<summary><strong>" + (.advertised_kafka_api.name | html) + "</strong> " +
      "<span>key " + (.advertised_kafka_api.key | tostring) + ", v" +
      (.advertised_kafka_api.min_version | tostring) + "-v" +
      (.advertised_kafka_api.max_version | tostring) + "</span></summary>\n" +
    "<p><strong>Release status:</strong> " + (.status | html) + "</p>\n" +
    "<p><strong>Current constraint:</strong> " +
      ((.limitations | join(" ")) | html) + "</p>\n" +
    "</details>\n"
  ' "$MANIFEST"
} >"$fragment"

awk -v fragment="$fragment" '
  /<!-- capability-matrix:start -->/ {
    print
    while ((getline line < fragment) > 0) print line
    close(fragment)
    replacing = 1
    next
  }
  /<!-- capability-matrix:end -->/ {
    replacing = 0
    print
    next
  }
  !replacing { print }
' "$PAGE" >"$page_tmp"

if [[ "$MODE" == "--check" ]]; then
  if ! cmp -s "$PAGE" "$page_tmp"; then
    echo "generated compatibility page is stale; run scripts/render-capabilities.sh" >&2
    diff -u "$PAGE" "$page_tmp" || true
    exit 1
  fi
  echo "capability manifest and generated page are current for $documented_release"
else
  mv "$page_tmp" "$PAGE"
  echo "rendered ${PAGE#"$ROOT"/} for $documented_release"
fi
